FROM golang:1.16-alpine AS tools

ENV DOCKERIZE_VERSION v0.6.1
RUN go install github.com/jwilder/dockerize@$DOCKERIZE_VERSION
RUN go install github.com/cosmtrek/air@latest

FROM golang:1.16-alpine
WORKDIR /app

RUN apk --no-cache add tzdata

COPY --from=tools /go/bin/dockerize /usr/local/bin/
COPY --from=tools /go/bin/air /usr/local/bin/